// https://github.com/alexjoverm/typescript-library-starter/blob/master/rollup.config.ts
// https://github.com/acornjs/acorn/blob/master/acorn-walk/rollup.config.js
// https://medium.com/@augustas.skaburskas/publishing-a-typescript-npm-package-4b284ecd1b52

// why not the office plugin https://github.com/rollup/plugins/issues/287
import typescript from 'rollup-plugin-typescript2';
import dts from 'rollup-plugin-dts';

import pkg from './package.json';

export default [
  {
    input: 'src/href.ts',
    output: [
      {
        file: pkg.exports.require,
        name: 'href-js',
        format: 'umd',
        sourcemap: true,
      },
      { file: pkg.exports.import, format: 'es', sourcemap: true },
    ],
    plugins: [typescript()],
  },
  {
    // using d.ts files generated by ⬆️
    input: 'dist/href.d.ts',
    output: { file: pkg.types },
    plugins: [dts()],
  },
];
